" Make vim more useful
set nocompatible

" Vundle
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
source ~/dotfiles/vim/plugins
call vundle#end()
filetype plugin indent on

autocmd QuickFixCmdPost [^l]* nested cwindow
autocmd QuickFixCmdPost    l* nested lwindow

" markdown
autocmd BufNewFile,BufReadPost *.md set filetype=markdown

" configure NERDTree
map <C-t> :NERDTreeFocus<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

" indent guides
let g:indent_guides_enable_on_vim_startup = 1

" Hound config
let g:hound_base_url = "localhost"
let g:hound_port = "6080"
map <C-f> :Hound<space>

" Solarized colorscheme
colorscheme solarized
set background=light

set t_Co=256

" Syntax highlighting
syntax enable
" Line numbers
set number
" Current line highlight
set cursorline
" Show the cursor position
set ruler
" Don’t reset cursor to start of line when moving around.
set nostartofline

" “invisible” characters
set lcs=tab:▸\ ,trail:·,eol:¬,nbsp:_
set list

" Optimize for fast terminal connections
set ttyfast
" Use UTF-8 without BOM
set encoding=utf-8 nobomb
" Change mapleader
let mapleader=","

" Space-tabs
set expandtab
" Tab size
set tabstop=2
set shiftwidth=2
" Indent behavior
set autoindent
set smartindent

" make backspace work like most other apps
set backspace=2

" Highlight searches
set hlsearch
" Highlight dynamically as pattern is typed
set incsearch

" Always show status line
set laststatus=2
" Show the current mode
set showmode
" Show the filename in the window titlebar
set title
" Show the (partial) command as it’s being typed
set showcmd
" Disable error bells
set noerrorbells
" Don’t show the intro message when starting vim
set shortmess=atI
" Start scrolling three lines before the horizontal window border
set scrolloff=3
" Enable mouse in all modes
set mouse=a

" max out at 80 characters bro
highlight OverLength ctermbg=darkred ctermfg=white guibg=#592929
match OverLength /\%>80v.\+/

" disable arrow keys -- don't be a bitch
map   <up>    <nop>
map   <down>  <nop>
map   <left>  <nop>
map   <right> <nop>
imap  <up>    <nop>
imap  <down>  <nop>
imap  <left>  <nop>
imap  <right> <nop>

" make YCM compatible with UltiSnips (using supertab)
let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']
let g:SuperTabDefaultCompletionType = '<C-n>'

" ctrlp config
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*/node_modules/*,*/dist/*,*/build/*,*resources*,*/data/*

" Neomake
autocmd! BufWritePost * Neomake
let g:neomake_open_list = 2
let g:neomake_list_height = 6
let g:neomake_javascript_enabled_makers = ['flow', 'eslint']

" press ESC to exit terminal model
tnoremap <Esc> <C-\><C-n>

" import a local profile
source ~/.vim_profile
